image: node:latest

before_script:
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages: 
    - build
    - test
    - deploy

build:
   stage: build
   script:
    - npm install
   except:
    - master
test:
  stage: test
  script:
    - npm install
    - npm run build
  except: 
    - develop
    - master

deployment:
  stage: deploy
  script:
  - npm i
  - sleep 0.1
  - npm run build
  - scp -r build/ root@95.217.8.24:/var/www/gametracer-front/
  only:
    - develop
    - master
